-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Create post_embeddings table
CREATE TABLE IF NOT EXISTS post_embeddings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  embedding vector(768), -- Gemini embedding-001 produces 768-dimensional vectors
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(post_id)
);

-- Create index for faster similarity searches
CREATE INDEX IF NOT EXISTS post_embeddings_embedding_idx ON post_embeddings 
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- Create index on post_id for faster lookups
CREATE INDEX IF NOT EXISTS post_embeddings_post_id_idx ON post_embeddings(post_id);

-- Enable RLS (Row Level Security)
ALTER TABLE post_embeddings ENABLE ROW LEVEL SECURITY;

-- Policy: Everyone can view embeddings
CREATE POLICY "Embeddings are viewable by everyone" 
ON post_embeddings FOR SELECT 
USING (true);

-- Policy: Authenticated users can insert embeddings
CREATE POLICY "Authenticated users can create embeddings" 
ON post_embeddings FOR INSERT 
WITH CHECK (true);

-- Policy: Authenticated users can update their own post embeddings
CREATE POLICY "Users can update their own post embeddings" 
ON post_embeddings FOR UPDATE 
USING (
  EXISTS (
    SELECT 1 FROM posts 
    WHERE posts.id = post_embeddings.post_id 
    AND posts.user_id = auth.uid()
  )
);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_post_embeddings_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to automatically update updated_at
CREATE TRIGGER update_post_embeddings_updated_at_trigger
BEFORE UPDATE ON post_embeddings
FOR EACH ROW
EXECUTE FUNCTION update_post_embeddings_updated_at();

-- Function to find similar posts based on embeddings
CREATE OR REPLACE FUNCTION find_similar_posts(
  query_embedding vector(768),
  match_tag_id UUID,
  match_ward_no INTEGER,
  similarity_threshold FLOAT DEFAULT 0.4,
  match_count INTEGER DEFAULT 5
)
RETURNS TABLE (
  post_id UUID,
  title TEXT,
  description TEXT,
  similarity FLOAT
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    p.id,
    p.title,
    p.description,
    1 - (pe.embedding <=> query_embedding) as similarity
  FROM post_embeddings pe
  JOIN posts p ON pe.post_id = p.id
  WHERE 
    p.tag_id = match_tag_id
    AND p.ward_no = match_ward_no
    AND 1 - (pe.embedding <=> query_embedding) >= similarity_threshold
  ORDER BY pe.embedding <=> query_embedding
  LIMIT match_count;
END;
$$ LANGUAGE plpgsql;

-- Comment on the table
COMMENT ON TABLE post_embeddings IS 'Stores vector embeddings for posts to enable semantic similarity search';
COMMENT ON COLUMN post_embeddings.embedding IS 'Vector embedding generated by Gemini AI (768 dimensions)';
